version: '2'
services:
    proyectoherokuposgress-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/proyectoHerokuPosgress/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=proyectoHerokuPosgress
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
